version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/packages/pip"
    schedule:
      interval: "daily"

    - package-ecosystem: "pip"
    directory: "/shortcuts"
    schedule:
      interval: "daily"